#Infrared config
infrared_pin:
  pin_number: 18
  direction: in
  type: DIGITAL
  open_value: 1
  blocked_value: 0
  read_interval: 100

Hardware_output:
  speaker:
    available: false
    pin_number: 23
    direction: out
  buzzer:
    available: true
    pin_number: 24
    direction: out
    volume: 50
  LED:
    warning:
      available: true
      pin_number: 25
      direction: out
    traffic:
      available: true
      pin_number: 26
      direction: out

Notifications:
  enabled: true
  sender_email: candolpd@gmail.com
  receiver_email: 3112938d@student.gla.ac.uk,candolpd@gmail.com
  smtp_server: smtp.gmail.com
  smtp_port: 587
  smtp_password:
  smtp_username: candolpd@gmail.com
  template_file: templates/email.html
  resent_time: 10

Camera:
  enabled: false
  output_file: output.avi

AI:
  enabled: false
  model_file: models/model.tflite
  model: OPENCV


